// ─────────────────────────────────────────────
// Coaching Profile — question configuration
//
// Each section defines its questions declaratively.
// The form renderer reads this config to build the UI.
// ─────────────────────────────────────────────

import type { SectionConfig } from "./types";

export const SECTION_CONFIGS: SectionConfig[] = [
  {
    sectionKey: "identity_life_context",
    title: "Identity & Life Context",
    questions: [
      {
        questionKey: "age",
        label: "How old are you?",
        inputType: "number",
        required: true,
      },
      {
        questionKey: "biological_sex",
        label: "What is your biological sex?",
        inputType: "single_select",
        options: ["Male", "Female", "Prefer not to say"],
        required: false,
      },
      {
        questionKey: "life_season",
        label: "Which best describes your current life season?",
        inputType: "single_select",
        options: [
          "Student or early career",
          "Building career",
          "Raising young children",
          "Established career",
          "Empty nester or life transition",
          "Retired or semi-retired",
          "Other",
        ],
        required: false,
      },
      {
        questionKey: "workday_description",
        label: "What does your typical workday look like?",
        inputType: "multi_select",
        options: [
          "Desk or office work (mostly seated)",
          "On my feet all day",
          "High mental stress or decision-making work",
          "Variable schedule or shifts",
          "Work from home",
          "Multiple jobs or roles",
          "Retired / not currently working",
        ],
        required: false,
      },
      {
        questionKey: "health_motivation",
        label: "What made you decide to start improving your health now?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "prior_attempts",
        label: "Have you tried to improve your health or fitness before?",
        inputType: "single_select",
        options: [
          "Yes, multiple times",
          "Yes, once or twice",
          "This is my first serious attempt",
        ],
        required: false,
      },
      {
        questionKey: "prior_attempts_detail",
        label: "If yes, what happened previously? What worked and what caused it to fall apart?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "support_system",
        label: "Who in your life is supportive of your health goals?",
        inputType: "multi_select",
        options: [
          "My partner or spouse is supportive",
          "My partner knows but is not particularly supportive",
          "Close friends encourage me",
          "No one really knows yet",
          "I am doing this alone by choice",
          "Family members may make it harder",
        ],
        required: false,
      },
      {
        questionKey: "training_days",
        label: "Realistically, how many days per week can you train intentionally?",
        inputType: "single_select",
        options: [
          "2 days",
          "3 days",
          "4 days",
          "5 days",
          "More than 5 days",
        ],
        required: false,
      },
      {
        questionKey: "training_time",
        label: "What time of day usually works best for training?",
        inputType: "single_select",
        options: [
          "Early morning (before 7am)",
          "Morning (7–9am)",
          "Midday",
          "Afternoon (3–5pm)",
          "Evening (after 5pm)",
          "My schedule varies",
        ],
        required: false,
      },
      {
        questionKey: "biggest_obstacles",
        label: "What are the two biggest things most likely to get in your way?",
        inputType: "multi_select",
        options: [
          "Time and schedule chaos",
          "Low energy or fatigue",
          "Stress eating or emotional eating",
          "Staying consistent when motivation drops",
          "Injuries or physical limitations",
          "Social situations and travel",
          "All-or-nothing thinking",
          "Not sure what plan to follow",
          "Cost or access to resources",
        ],
        required: false,
      },
      {
        questionKey: "self_identity",
        label: "Finish this sentence — \"When it comes to my health and fitness, I am someone who…\"",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "six_month_vision",
        label: "Six months from now, if this worked, what would be different in your life?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "accountability_style",
        label: "How do you prefer to be held accountable when things get difficult?",
        inputType: "single_select",
        options: [
          "Be direct with me and show the data",
          "Acknowledge effort first, then address problems",
          "Ask questions and let me reflect",
          "Just check in consistently",
        ],
        required: false,
      },
      {
        questionKey: "faith_integration",
        label: "Would you like faith or personal values integrated into coaching?",
        inputType: "single_select",
        options: [
          "Yes, my faith is important to my discipline",
          "Somewhat, I am open to it",
          "No, keep coaching practical",
        ],
        required: false,
      },
    ],
  },
  {
    sectionKey: "health_history",
    title: "Health History",
    questions: [
      {
        questionKey: "injuries_limitations",
        label: "Do you currently have any injuries, joint pain, or physical limitations that affect your training?",
        inputType: "single_select",
        options: ["Yes", "No"],
        required: true,
      },
      {
        questionKey: "injuries_detail",
        label: "If yes, what area(s) are affected and what does it limit you from doing?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "medical_conditions",
        label: "Do you have any diagnosed medical conditions that affect your energy, metabolism, or ability to train?",
        inputType: "multi_select",
        options: [
          "Thyroid condition",
          "Type 1 or Type 2 diabetes / insulin resistance",
          "High blood pressure or cardiovascular condition",
          "PCOS",
          "Autoimmune condition",
          "Chronic pain condition",
          "Mental health diagnosis",
          "None of the above",
          "Other",
        ],
        required: false,
      },
      {
        questionKey: "medications_supplements",
        label: "Are you currently taking any medications or supplements that may affect your energy, appetite, or body composition?",
        inputType: "single_select",
        options: ["Yes", "No"],
        required: false,
      },
      {
        questionKey: "medications_detail",
        label: "If yes, please list the medications or supplements you are taking.",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "hormonal_female",
        label: "For female clients — where are you in your hormonal journey?",
        inputType: "single_select",
        options: [
          "Regular menstrual cycles",
          "Irregular cycles",
          "Possibly perimenopause",
          "Diagnosed perimenopause",
          "Postmenopausal",
          "Pregnant",
          "Postpartum (within 18 months)",
          "On hormonal birth control",
          "On hormone replacement therapy",
          "Not applicable / male",
        ],
        required: false,
      },
      {
        questionKey: "hormonal_male",
        label: "For male clients — have you noticed any of the following in the past year?",
        inputType: "multi_select",
        options: [
          "Increased fatigue despite sleep",
          "Difficulty building or maintaining muscle",
          "Increased fat around the midsection",
          "Reduced motivation or drive",
          "Lower mood or brain fog",
          "Reduced libido",
          "None of the above / not applicable",
        ],
        required: false,
      },
      {
        questionKey: "energy_level",
        label: "How would you rate your energy levels on a typical day?",
        inputType: "scale",
        scaleMin: 1,
        scaleMax: 10,
        helperText: "1 = chronically exhausted, 10 = consistently energized",
        required: false,
      },
      {
        questionKey: "bloodwork",
        label: "Have you had bloodwork done for hormones, metabolic health, or nutrient levels?",
        inputType: "single_select",
        options: [
          "Yes, within the last 12 months and results were normal",
          "Yes, within the last 12 months and something was flagged",
          "Yes, but more than 2 years ago",
          "No, I have never had this type of bloodwork",
          "I am not sure",
        ],
        required: false,
      },
      {
        questionKey: "bloodwork_flagged",
        label: "If something was flagged in your bloodwork, what was it?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "disordered_eating",
        label: "Do you have a history of disordered eating or a difficult relationship with food?",
        inputType: "single_select",
        options: [
          "No, my relationship with food has generally been healthy",
          "I have had difficult periods in the past",
          "It is something I am currently working through",
          "Yes, it is a significant ongoing challenge",
          "Prefer not to say",
        ],
        required: false,
      },
      {
        questionKey: "health_trend",
        label: "How would you rate your overall physical health compared to five years ago?",
        inputType: "single_select",
        options: [
          "Significantly better",
          "About the same",
          "Somewhat worse",
          "Significantly worse",
          "I was not healthy five years ago either",
        ],
        required: false,
      },
      {
        questionKey: "surgery_illness",
        label: "Have you had surgery, significant illness, or hospitalization in the last three years that still affects you?",
        inputType: "single_select",
        options: ["Yes", "No"],
        required: false,
      },
      {
        questionKey: "surgery_detail",
        label: "If yes, briefly describe the surgery, illness, or hospitalization.",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "tobacco_cannabis",
        label: "Do you smoke, use tobacco, or regularly use cannabis?",
        inputType: "multi_select",
        options: [
          "I smoke cigarettes or use tobacco products",
          "I use cannabis regularly",
          "Neither",
        ],
        required: false,
      },
      {
        questionKey: "alcohol_weekly",
        label: "How many alcoholic drinks do you typically have in a week?",
        inputType: "single_select",
        options: [
          "None",
          "1–3 drinks",
          "4–7 drinks",
          "8–14 drinks",
          "More than 14 drinks",
        ],
        required: false,
      },
    ],
  },
  {
    sectionKey: "training_background",
    title: "Training Background",
    questions: [
      {
        questionKey: "experience_level",
        label: "How would you describe your current training experience level?",
        inputType: "single_select",
        options: [
          "Beginner — I have little to no consistent training history",
          "Novice — I have trained on and off but not consistently for more than 6 months",
          "Intermediate — I have trained consistently for 1–3 years",
          "Advanced — I have trained consistently for 3+ years with progressive programming",
          "Experienced athlete — competitive background or elite training history",
        ],
        required: true,
      },
      {
        questionKey: "training_types",
        label: "What type of training have you done most consistently?",
        inputType: "multi_select",
        options: [
          "Resistance training / weightlifting",
          "CrossFit or functional fitness",
          "Running or endurance sports",
          "Group fitness classes (spin, HIIT, boot camp, etc.)",
          "Yoga or Pilates",
          "Team sports",
          "Martial arts or combat sports",
          "Walking as primary movement",
          "I have not trained consistently — starting fresh",
        ],
        required: false,
      },
      {
        questionKey: "current_training_days",
        label: "How many days per week are you currently training (any intentional exercise)?",
        inputType: "single_select",
        options: [
          "0 days — I am not currently training",
          "1–2 days",
          "3–4 days",
          "5–6 days",
          "7 days — I train every day",
        ],
        required: false,
      },
      {
        questionKey: "gym_access",
        label: "What kind of training environment do you currently have access to?",
        inputType: "single_select",
        options: [
          "Full commercial gym",
          "Functional fitness / CrossFit gym",
          "Small gym or limited equipment",
          "Home gym setup",
          "Minimal equipment at home",
          "No equipment",
        ],
        required: false,
      },
      {
        questionKey: "missed_training_reason",
        label: "When you miss training sessions, what is usually the reason? (Select your top 2)",
        inputType: "multi_select",
        options: [
          "Too busy or schedule ran over",
          "Too tired or low energy",
          "Sore or injured",
          "Traveling or away from home",
          "Motivation or mental resistance",
          "Life responsibilities (kids, work, family)",
          "I rarely miss training",
        ],
        required: false,
      },
      {
        questionKey: "hard_workout_response",
        label: "How do you usually respond when a workout is harder than you expected?",
        inputType: "single_select",
        options: [
          "I push through and finish even if I have to scale back",
          "I push through at the same level and refuse to scale",
          "I sometimes stop early when it gets uncomfortable",
          "I tend to avoid workouts I expect to be very hard",
        ],
        required: false,
      },
      {
        questionKey: "aerobic_base",
        label: "On a scale of 1–10, how strong is your aerobic base?",
        inputType: "scale",
        scaleMin: 1,
        scaleMax: 10,
        helperText: "1 = I gas out quickly, 10 = I can sustain moderate effort for 20+ minutes",
        required: false,
      },
      {
        questionKey: "structured_training_history",
        label: "Have you ever followed a structured training program or training log?",
        inputType: "single_select",
        options: [
          "Yes — I consistently follow structured programs",
          "Yes — sometimes but not consistently",
          "No — I usually just train randomly",
          "No — I am completely new to structured training",
        ],
        required: false,
      },
      {
        questionKey: "movement_limitations",
        label: "Do you have any movement limitations, chronic pain, or areas that consistently bother you during training?",
        inputType: "multi_select",
        options: [
          "Lower back pain",
          "Knee pain",
          "Hip tightness or limited range of motion",
          "Shoulder pain during pressing or overhead work",
          "Ankle mobility limitations",
          "Neck or upper back tension",
          "Wrist or elbow discomfort",
          "None — I train pain-free",
        ],
        required: false,
      },
      {
        questionKey: "longest_consistency_streak",
        label: "What is the longest period of time you have ever trained consistently?",
        inputType: "single_select",
        options: [
          "Less than 1 month",
          "1–3 months",
          "3–6 months",
          "6–12 months",
          "More than a year",
        ],
        required: false,
      },
      {
        questionKey: "best_training_week",
        label: "What does your best week of training look like when everything is going well?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "training_enjoyment",
        label: "What type of training do you genuinely enjoy or look forward to?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "training_avoidance",
        label: "What type of training do you dread or consistently avoid?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "past_training_success",
        label: "When you were most successful with your fitness in the past, what were you doing differently?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "past_training_failure",
        label: "When past fitness attempts failed, what usually caused you to stop?",
        inputType: "textarea",
        required: false,
      },
    ],
  },
  { sectionKey: "nutrition_habits",          title: "Nutrition Habits",          questions: [] },
  { sectionKey: "lifestyle_recovery",        title: "Lifestyle & Recovery",      questions: [] },
  { sectionKey: "goals_vision",             title: "Goals & Vision",            questions: [] },
  { sectionKey: "mindset_accountability",    title: "Mindset & Accountability",  questions: [] },
  { sectionKey: "spirit_new_beginnings",     title: "Spirit & New Beginnings",   questions: [] },
];

/** Look up a section config by its key */
export function getSectionConfig(sectionKey: string): SectionConfig | undefined {
  return SECTION_CONFIGS.find((s) => s.sectionKey === sectionKey);
}

/** Look up a section config by its display title */
export function getSectionByTitle(title: string): SectionConfig | undefined {
  return SECTION_CONFIGS.find((s) => s.title === title);
}
