// ─────────────────────────────────────────────
// Coaching Profile — question configuration
//
// Each section defines its questions declaratively.
// The form renderer reads this config to build the UI.
// ─────────────────────────────────────────────

import type { SectionConfig } from "./types";

export const SECTION_CONFIGS: SectionConfig[] = [
  {
    sectionKey: "identity_life_context",
    title: "Identity & Life Context",
    questions: [
      {
        questionKey: "age",
        label: "How old are you?",
        inputType: "number",
        required: true,
      },
      {
        questionKey: "biological_sex",
        label: "What is your biological sex?",
        inputType: "single_select",
        options: ["Male", "Female", "Prefer not to say"],
        required: false,
      },
      {
        questionKey: "life_season",
        label: "Which best describes your current life season?",
        inputType: "single_select",
        options: [
          "Student or early career",
          "Building career",
          "Raising young children",
          "Established career",
          "Empty nester or life transition",
          "Retired or semi-retired",
          "Other",
        ],
        required: false,
      },
      {
        questionKey: "workday_description",
        label: "What does your typical workday look like?",
        inputType: "multi_select",
        options: [
          "Desk or office work (mostly seated)",
          "On my feet all day",
          "High mental stress or decision-making work",
          "Variable schedule or shifts",
          "Work from home",
          "Multiple jobs or roles",
          "Retired / not currently working",
        ],
        required: false,
      },
      {
        questionKey: "health_motivation",
        label: "What made you decide to start improving your health now?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "prior_attempts",
        label: "Have you tried to improve your health or fitness before?",
        inputType: "single_select",
        options: [
          "Yes, multiple times",
          "Yes, once or twice",
          "This is my first serious attempt",
        ],
        required: false,
      },
      {
        questionKey: "prior_attempts_detail",
        label: "If yes, what happened previously? What worked and what caused it to fall apart?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "support_system",
        label: "Who in your life is supportive of your health goals?",
        inputType: "multi_select",
        options: [
          "My partner or spouse is supportive",
          "My partner knows but is not particularly supportive",
          "Close friends encourage me",
          "No one really knows yet",
          "I am doing this alone by choice",
          "Family members may make it harder",
        ],
        required: false,
      },
      {
        questionKey: "training_days",
        label: "Realistically, how many days per week can you train intentionally?",
        inputType: "single_select",
        options: [
          "2 days",
          "3 days",
          "4 days",
          "5 days",
          "More than 5 days",
        ],
        required: false,
      },
      {
        questionKey: "training_time",
        label: "What time of day usually works best for training?",
        inputType: "single_select",
        options: [
          "Early morning (before 7am)",
          "Morning (7–9am)",
          "Midday",
          "Afternoon (3–5pm)",
          "Evening (after 5pm)",
          "My schedule varies",
        ],
        required: false,
      },
      {
        questionKey: "biggest_obstacles",
        label: "What are the two biggest things most likely to get in your way?",
        inputType: "multi_select",
        options: [
          "Time and schedule chaos",
          "Low energy or fatigue",
          "Stress eating or emotional eating",
          "Staying consistent when motivation drops",
          "Injuries or physical limitations",
          "Social situations and travel",
          "All-or-nothing thinking",
          "Not sure what plan to follow",
          "Cost or access to resources",
        ],
        required: false,
      },
      {
        questionKey: "self_identity",
        label: "Finish this sentence — \"When it comes to my health and fitness, I am someone who…\"",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "six_month_vision",
        label: "Six months from now, if this worked, what would be different in your life?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "accountability_style",
        label: "How do you prefer to be held accountable when things get difficult?",
        inputType: "single_select",
        options: [
          "Be direct with me and show the data",
          "Acknowledge effort first, then address problems",
          "Ask questions and let me reflect",
          "Just check in consistently",
        ],
        required: false,
      },
      {
        questionKey: "faith_integration",
        label: "Would you like faith or personal values integrated into coaching?",
        inputType: "single_select",
        options: [
          "Yes, my faith is important to my discipline",
          "Somewhat, I am open to it",
          "No, keep coaching practical",
        ],
        required: false,
      },
    ],
  },
  {
    sectionKey: "health_history",
    title: "Health History",
    questions: [
      {
        questionKey: "injuries_limitations",
        label: "Do you currently have any injuries, joint pain, or physical limitations that affect your training?",
        inputType: "single_select",
        options: ["Yes", "No"],
        required: true,
      },
      {
        questionKey: "injuries_detail",
        label: "If yes, what area(s) are affected and what does it limit you from doing?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "medical_conditions",
        label: "Do you have any diagnosed medical conditions that affect your energy, metabolism, or ability to train?",
        inputType: "multi_select",
        options: [
          "Thyroid condition",
          "Type 1 or Type 2 diabetes / insulin resistance",
          "High blood pressure or cardiovascular condition",
          "PCOS",
          "Autoimmune condition",
          "Chronic pain condition",
          "Mental health diagnosis",
          "None of the above",
          "Other",
        ],
        required: false,
      },
      {
        questionKey: "medications_supplements",
        label: "Are you currently taking any medications or supplements that may affect your energy, appetite, or body composition?",
        inputType: "single_select",
        options: ["Yes", "No"],
        required: false,
      },
      {
        questionKey: "medications_detail",
        label: "If yes, please list the medications or supplements you are taking.",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "hormonal_female",
        label: "For female clients — where are you in your hormonal journey?",
        inputType: "single_select",
        options: [
          "Regular menstrual cycles",
          "Irregular cycles",
          "Possibly perimenopause",
          "Diagnosed perimenopause",
          "Postmenopausal",
          "Pregnant",
          "Postpartum (within 18 months)",
          "On hormonal birth control",
          "On hormone replacement therapy",
          "Not applicable / male",
        ],
        required: false,
      },
      {
        questionKey: "hormonal_male",
        label: "For male clients — have you noticed any of the following in the past year?",
        inputType: "multi_select",
        options: [
          "Increased fatigue despite sleep",
          "Difficulty building or maintaining muscle",
          "Increased fat around the midsection",
          "Reduced motivation or drive",
          "Lower mood or brain fog",
          "Reduced libido",
          "None of the above / not applicable",
        ],
        required: false,
      },
      {
        questionKey: "energy_level",
        label: "How would you rate your energy levels on a typical day?",
        inputType: "scale",
        scaleMin: 1,
        scaleMax: 10,
        helperText: "1 = chronically exhausted, 10 = consistently energized",
        required: false,
      },
      {
        questionKey: "bloodwork",
        label: "Have you had bloodwork done for hormones, metabolic health, or nutrient levels?",
        inputType: "single_select",
        options: [
          "Yes, within the last 12 months and results were normal",
          "Yes, within the last 12 months and something was flagged",
          "Yes, but more than 2 years ago",
          "No, I have never had this type of bloodwork",
          "I am not sure",
        ],
        required: false,
      },
      {
        questionKey: "bloodwork_flagged",
        label: "If something was flagged in your bloodwork, what was it?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "disordered_eating",
        label: "Do you have a history of disordered eating or a difficult relationship with food?",
        inputType: "single_select",
        options: [
          "No, my relationship with food has generally been healthy",
          "I have had difficult periods in the past",
          "It is something I am currently working through",
          "Yes, it is a significant ongoing challenge",
          "Prefer not to say",
        ],
        required: false,
      },
      {
        questionKey: "health_trend",
        label: "How would you rate your overall physical health compared to five years ago?",
        inputType: "single_select",
        options: [
          "Significantly better",
          "About the same",
          "Somewhat worse",
          "Significantly worse",
          "I was not healthy five years ago either",
        ],
        required: false,
      },
      {
        questionKey: "surgery_illness",
        label: "Have you had surgery, significant illness, or hospitalization in the last three years that still affects you?",
        inputType: "single_select",
        options: ["Yes", "No"],
        required: false,
      },
      {
        questionKey: "surgery_detail",
        label: "If yes, briefly describe the surgery, illness, or hospitalization.",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "tobacco_cannabis",
        label: "Do you smoke, use tobacco, or regularly use cannabis?",
        inputType: "multi_select",
        options: [
          "I smoke cigarettes or use tobacco products",
          "I use cannabis regularly",
          "Neither",
        ],
        required: false,
      },
      {
        questionKey: "alcohol_weekly",
        label: "How many alcoholic drinks do you typically have in a week?",
        inputType: "single_select",
        options: [
          "None",
          "1–3 drinks",
          "4–7 drinks",
          "8–14 drinks",
          "More than 14 drinks",
        ],
        required: false,
      },
    ],
  },
  {
    sectionKey: "training_background",
    title: "Training Background",
    questions: [
      {
        questionKey: "experience_level",
        label: "How would you describe your current training experience level?",
        inputType: "single_select",
        options: [
          "Beginner — I have little to no consistent training history",
          "Novice — I have trained on and off but not consistently for more than 6 months",
          "Intermediate — I have trained consistently for 1–3 years",
          "Advanced — I have trained consistently for 3+ years with progressive programming",
          "Experienced athlete — competitive background or elite training history",
        ],
        required: true,
      },
      {
        questionKey: "training_types",
        label: "What type of training have you done most consistently?",
        inputType: "multi_select",
        options: [
          "Resistance training / weightlifting",
          "CrossFit or functional fitness",
          "Running or endurance sports",
          "Group fitness classes (spin, HIIT, boot camp, etc.)",
          "Yoga or Pilates",
          "Team sports",
          "Martial arts or combat sports",
          "Walking as primary movement",
          "I have not trained consistently — starting fresh",
        ],
        required: false,
      },
      {
        questionKey: "current_training_days",
        label: "How many days per week are you currently training (any intentional exercise)?",
        inputType: "single_select",
        options: [
          "0 days — I am not currently training",
          "1–2 days",
          "3–4 days",
          "5–6 days",
          "7 days — I train every day",
        ],
        required: false,
      },
      {
        questionKey: "gym_access",
        label: "What kind of training environment do you currently have access to?",
        inputType: "single_select",
        options: [
          "Full commercial gym",
          "Functional fitness / CrossFit gym",
          "Small gym or limited equipment",
          "Home gym setup",
          "Minimal equipment at home",
          "No equipment",
        ],
        required: false,
      },
      {
        questionKey: "missed_training_reason",
        label: "When you miss training sessions, what is usually the reason? (Select your top 2)",
        inputType: "multi_select",
        options: [
          "Too busy or schedule ran over",
          "Too tired or low energy",
          "Sore or injured",
          "Traveling or away from home",
          "Motivation or mental resistance",
          "Life responsibilities (kids, work, family)",
          "I rarely miss training",
        ],
        required: false,
      },
      {
        questionKey: "hard_workout_response",
        label: "How do you usually respond when a workout is harder than you expected?",
        inputType: "single_select",
        options: [
          "I push through and finish even if I have to scale back",
          "I push through at the same level and refuse to scale",
          "I sometimes stop early when it gets uncomfortable",
          "I tend to avoid workouts I expect to be very hard",
        ],
        required: false,
      },
      {
        questionKey: "aerobic_base",
        label: "On a scale of 1–10, how strong is your aerobic base?",
        inputType: "scale",
        scaleMin: 1,
        scaleMax: 10,
        helperText: "1 = I gas out quickly, 10 = I can sustain moderate effort for 20+ minutes",
        required: false,
      },
      {
        questionKey: "structured_training_history",
        label: "Have you ever followed a structured training program or training log?",
        inputType: "single_select",
        options: [
          "Yes — I consistently follow structured programs",
          "Yes — sometimes but not consistently",
          "No — I usually just train randomly",
          "No — I am completely new to structured training",
        ],
        required: false,
      },
      {
        questionKey: "movement_limitations",
        label: "Do you have any movement limitations, chronic pain, or areas that consistently bother you during training?",
        inputType: "multi_select",
        options: [
          "Lower back pain",
          "Knee pain",
          "Hip tightness or limited range of motion",
          "Shoulder pain during pressing or overhead work",
          "Ankle mobility limitations",
          "Neck or upper back tension",
          "Wrist or elbow discomfort",
          "None — I train pain-free",
        ],
        required: false,
      },
      {
        questionKey: "longest_consistency_streak",
        label: "What is the longest period of time you have ever trained consistently?",
        inputType: "single_select",
        options: [
          "Less than 1 month",
          "1–3 months",
          "3–6 months",
          "6–12 months",
          "More than a year",
        ],
        required: false,
      },
      {
        questionKey: "best_training_week",
        label: "What does your best week of training look like when everything is going well?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "training_enjoyment",
        label: "What type of training do you genuinely enjoy or look forward to?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "training_avoidance",
        label: "What type of training do you dread or consistently avoid?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "past_training_success",
        label: "When you were most successful with your fitness in the past, what were you doing differently?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "past_training_failure",
        label: "When past fitness attempts failed, what usually caused you to stop?",
        inputType: "textarea",
        required: false,
      },
    ],
  },
  {
    sectionKey: "nutrition_habits",
    title: "Nutrition Habits",
    questions: [
      {
        questionKey: "meal_frequency",
        label: "How many meals or eating occasions do you have on a typical day?",
        inputType: "single_select",
        options: [
          "1 meal or less",
          "2 meals",
          "3 meals",
          "3 meals plus snacks",
          "I graze throughout the day without distinct meals",
          "It varies significantly day to day",
        ],
        required: true,
      },
      {
        questionKey: "protein_intake_estimate",
        label: "On a typical day, roughly how much total protein do you eat?",
        inputType: "single_select",
        options: [
          "I have no idea",
          "Very little — I rarely think about protein",
          "Some — I include protein but probably not enough",
          "A moderate amount — maybe 80–120g daily",
          "A solid amount — probably 130–160g daily",
          "High protein — I actively hit 160g+ daily",
        ],
        required: false,
      },
      {
        questionKey: "breakfast_habit",
        label: "Do you eat breakfast?",
        inputType: "single_select",
        options: [
          "Yes — always, and it includes meaningful protein",
          "Yes — but it is usually carbs with little protein",
          "Sometimes — it depends on the day",
          "No — I am not hungry in the morning or I intermittent fast",
          "No — I never eat breakfast",
        ],
        required: false,
      },
      {
        questionKey: "eating_approach",
        label: "How would you describe your current eating approach?",
        inputType: "single_select",
        options: [
          "No plan — I eat whatever, whenever",
          "Loosely health-conscious but not structured",
          "I follow general guidelines",
          "I track macros or calories",
          "I follow a specific dietary protocol",
          "I have tried many approaches and nothing has stuck long-term",
        ],
        required: false,
      },
      {
        questionKey: "diet_restrictions_details",
        label: "If you follow a specific diet or have significant dietary restrictions, please describe them.",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "eat_out_frequency",
        label: "How often do you eat out or order takeout?",
        inputType: "single_select",
        options: [
          "Rarely — mostly home-cooked meals",
          "1–3 times per week",
          "4–6 times per week",
          "Daily or almost every meal",
        ],
        required: false,
      },
      {
        questionKey: "cravings_pattern",
        label: "Do you experience strong food cravings?",
        inputType: "multi_select",
        options: [
          "Yes — mostly in the evening after dinner",
          "Yes — in the afternoon, around 3–4pm",
          "Yes — when I am stressed or emotionally activated",
          "Yes — when I am bored or procrastinating",
          "Yes — right before or during my period",
          "Occasionally, but not a significant issue",
          "Rarely or never",
        ],
        required: false,
      },
      {
        questionKey: "cravings_details",
        label: "If you experience cravings, what do you typically crave?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "hydration_level",
        label: "How much water do you drink on a typical day?",
        inputType: "single_select",
        options: [
          "Less than 32 oz",
          "32–64 oz",
          "64–96 oz",
          "96+ oz",
          "I mostly drink coffee, soda, or other beverages",
        ],
        required: false,
      },
      {
        questionKey: "off_plan_response",
        label: "How do you usually respond after eating an unplanned meal or off-plan food?",
        inputType: "single_select",
        options: [
          "I log it and move on",
          "I feel some guilt but get back on track the next meal",
          "I often spiral — one bad meal becomes a bad day or bad week",
          "I use it as justification to take a full break from trying",
          "I do not follow a plan, so this does not apply",
        ],
        required: false,
      },
      {
        questionKey: "supplements_current",
        label: "Do you currently take any nutritional supplements?",
        inputType: "multi_select",
        options: [
          "Creatine monohydrate",
          "Protein powder",
          "Vitamin D",
          "Omega-3 / fish oil",
          "Multivitamin",
          "Pre-workout or caffeine supplements",
          "GLP-1 medication",
          "Other hormonal or medical supplements",
          "I do not currently take supplements",
        ],
        required: false,
      },
      {
        questionKey: "food_tracking_readiness",
        label: "How do you feel about tracking food in an app?",
        inputType: "single_select",
        options: [
          "I already do it and find it helpful",
          "I have tried it before — it was useful but unsustainable",
          "I have tried it before — it felt obsessive or created anxiety",
          "I am open to trying it",
          "I strongly prefer not to track",
        ],
        required: false,
      },
      {
        questionKey: "worst_nutrition_day",
        label: "On your worst nutrition days, what does that actually look like?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "nutrition_confusion",
        label: "Is there anything about food or nutrition you have always been confused about, or a belief you are not sure is accurate?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "meal_prep_reality",
        label: "How often do you prepare meals or snacks ahead of time?",
        inputType: "single_select",
        options: [
          "Almost never",
          "Occasionally",
          "A couple times per week",
          "Most days",
          "I regularly prepare food ahead of time",
        ],
        required: false,
      },
      {
        questionKey: "weekend_nutrition_difference",
        label: "How different are your eating habits on weekends compared to weekdays?",
        inputType: "single_select",
        options: [
          "About the same",
          "Slightly less structured on weekends",
          "Much less structured on weekends",
          "Weekends are usually where I get off track",
          "My schedule is too variable to tell",
        ],
        required: false,
      },
    ],
  },
  {
    sectionKey: "lifestyle_recovery",
    title: "Lifestyle & Recovery",
    questions: [
      {
        questionKey: "sleep_hours",
        label: "How many hours of sleep do you typically get on weeknights?",
        inputType: "single_select",
        options: [
          "Less than 5 hours",
          "5–6 hours",
          "6–7 hours",
          "7–8 hours",
          "8–9 hours",
          "More than 9 hours",
        ],
        required: true,
      },
      {
        questionKey: "sleep_quality",
        label: "How would you describe your sleep quality?",
        inputType: "single_select",
        options: [
          "I fall asleep easily and wake feeling rested",
          "I fall asleep fine but wake during the night or early",
          "I have trouble falling asleep",
          "I sleep the hours but rarely feel rested",
          "My sleep is severely disrupted",
        ],
        required: false,
      },
      {
        questionKey: "wake_time_consistency",
        label: "What time do you typically wake up, and is it consistent?",
        inputType: "single_select",
        options: [
          "Consistent wake time within 30 minutes, 7 days a week",
          "Consistent on weekdays but different on weekends",
          "Variable depending on the day",
          "I use an alarm on weekdays but sleep in significantly on weekends",
        ],
        required: false,
      },
      {
        questionKey: "bedtime_consistency",
        label: "How consistent is your bedtime?",
        inputType: "single_select",
        options: [
          "Very consistent — I go to bed around the same time most nights",
          "Fairly consistent on weekdays, less consistent on weekends",
          "Inconsistent — bedtime changes a lot depending on the day",
          "I do not have any real bedtime routine",
        ],
        required: false,
      },
      {
        questionKey: "stress_level",
        label: "How would you describe your current stress level?",
        inputType: "scale",
        scaleMin: 1,
        scaleMax: 10,
        helperText: "1 = very low and manageable, 10 = extremely high and overwhelming",
        required: false,
      },
      {
        questionKey: "stress_sources",
        label: "What is causing the most stress in your life right now?",
        inputType: "multi_select",
        options: [
          "Work demands or career uncertainty",
          "Financial pressure",
          "Relationship or family conflict",
          "Parenting or caregiving responsibilities",
          "Health concerns",
          "Feeling behind or overwhelmed by life in general",
          "Grief or significant loss",
          "I feel relatively low stress overall",
        ],
        required: false,
      },
      {
        questionKey: "stress_management_tools",
        label: "How do you currently manage stress when it gets high?",
        inputType: "multi_select",
        options: [
          "Exercise or physical activity",
          "Prayer, meditation, or quiet time",
          "Talking to someone I trust",
          "Eating for comfort",
          "Alcohol or substances",
          "Scrolling social media or watching content",
          "I do not have good stress management tools right now",
          "Other",
        ],
        required: false,
      },
      {
        questionKey: "stress_management_other",
        label: "If you selected Other, what do you do to manage stress?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "sedentary_hours",
        label: "How many hours per day do you spend sitting?",
        inputType: "single_select",
        options: [
          "Less than 4 hours",
          "4–6 hours",
          "6–8 hours",
          "8–10 hours",
          "More than 10 hours",
        ],
        required: false,
      },
      {
        questionKey: "daily_steps",
        label: "How many steps do you approximately take on a typical day?",
        inputType: "single_select",
        options: [
          "Under 3,000",
          "3,000–5,000",
          "5,000–8,000",
          "8,000–10,000",
          "10,000+",
          "I do not track steps",
        ],
        required: false,
      },
      {
        questionKey: "wearables",
        label: "Do you use any wearable technology to track health metrics?",
        inputType: "multi_select",
        options: [
          "Smart watch",
          "WHOOP",
          "Oura Ring",
          "Continuous glucose monitor",
          "I do not use wearables",
        ],
        required: false,
      },
      {
        questionKey: "rest_day_relationship",
        label: "Describe your relationship with rest days.",
        inputType: "single_select",
        options: [
          "I take them intentionally and use them well",
          "I take them but feel guilty",
          "I rarely take rest days",
          "I take too many rest days",
          "I have no real structure around rest days",
        ],
        required: false,
      },
      {
        questionKey: "caffeine_amount",
        label: "How much caffeine do you consume daily?",
        inputType: "single_select",
        options: [
          "None",
          "1 cup of coffee or tea, before noon",
          "2–3 cups, mostly in the morning",
          "2–3 cups, including the afternoon",
          "4+ cups — I rely heavily on caffeine",
        ],
        required: false,
      },
      {
        questionKey: "caffeine_latest_time",
        label: "What is the latest time of day you typically have caffeine?",
        inputType: "text",
        required: false,
      },
      {
        questionKey: "sunlight_exposure",
        label: "Do you get at least 10 minutes of outdoor sunlight on most days?",
        inputType: "single_select",
        options: [
          "Yes — regularly, especially in the morning",
          "Sometimes — depends on the season and schedule",
          "Rarely — I spend most of my day indoors",
          "Almost never — my schedule keeps me inside",
        ],
        required: false,
      },
      {
        questionKey: "seasonal_consistency_pattern",
        label: "Is there a season, month, or recurring pattern where your health and fitness usually falls apart? When is it hardest to stay consistent?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "life_margin",
        label: "How much margin do you feel like you have in your life right now?",
        inputType: "single_select",
        options: [
          "I have a good amount of margin and flexibility",
          "I have some margin, but not much",
          "I feel stretched pretty thin most of the time",
          "I feel maxed out and overloaded",
        ],
        required: false,
      },
    ],
  },
  {
    sectionKey: "goals_vision",
    title: "Goals & Vision",
    questions: [
      {
        questionKey: "primary_goal",
        label: "What is your primary goal right now?",
        inputType: "single_select",
        options: [
          "Lose body fat or change my body composition",
          "Build muscle and get stronger",
          "Improve fitness and athletic performance",
          "Feel better — more energy, less pain, better sleep",
          "Improve metabolic health",
          "Maintain what I have and age well",
          "Prepare for a specific event or athletic goal",
        ],
        required: true,
      },
      {
        questionKey: "secondary_goals",
        label: "Are there secondary goals that also matter to you?",
        inputType: "multi_select",
        options: [
          "Feel more confident in my body",
          "Keep up with my kids or grandkids",
          "Reduce reliance on medications",
          "Prevent disease or injury as I age",
          "Set an example for my family",
          "Compete in a sport or event",
          "Improve mental health, mood, or anxiety",
          "Rebuild after a health setback",
        ],
        required: false,
      },
      {
        questionKey: "target_weight",
        label: "If you have a specific weight goal, what is it?",
        inputType: "number",
        required: false,
      },
      {
        questionKey: "target_bodyfat",
        label: "If known, what is your target body fat percentage?",
        inputType: "number",
        required: false,
      },
      {
        questionKey: "goal_timeline",
        label: "By when would you ideally like to reach this goal?",
        inputType: "text",
        required: false,
      },
      {
        questionKey: "goal_importance",
        label: "How important is achieving this goal to you right now?",
        inputType: "scale",
        scaleMin: 1,
        scaleMax: 10,
        helperText: "1 = it would be nice, 10 = this matters more than almost anything",
        required: false,
      },
      {
        questionKey: "goal_confidence",
        label: "How confident are you that you can achieve this goal?",
        inputType: "scale",
        scaleMin: 1,
        scaleMax: 10,
        helperText: "1 = I am not sure I can do this, 10 = I am completely confident I can make this happen",
        required: false,
      },
      {
        questionKey: "goal_meaning",
        label: "What would achieving this goal mean to you beyond the physical change?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "past_goal_barriers",
        label: "What has stopped you from achieving this goal in the past?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "non_negotiables",
        label: "Is there anything you are unwilling to change or give up while pursuing this goal?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "goal_tradeoffs",
        label: "What are you willing to change or prioritize in order to reach this goal?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "success_30_days",
        label: "What would success look like in the next 30 days?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "success_90_days",
        label: "What would success look like in the next 90 days?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "success_1_year",
        label: "What would success look like in one year?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "event_driven_goal",
        label: "Is there a specific event, date, or milestone driving your timeline?",
        inputType: "single_select",
        options: [
          "Yes",
          "No — I am focused on long-term change",
        ],
        required: false,
      },
      {
        questionKey: "event_details",
        label: "If yes, what event or milestone and when is it?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "program_success_definition",
        label: "How will you personally define success from this program beyond just the scale or mirror?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "other_health_professionals",
        label: "Are you currently working with any other health professionals?",
        inputType: "multi_select",
        options: [
          "Primary care physician",
          "Endocrinologist or specialist",
          "Registered dietitian or nutritionist",
          "Therapist or mental health professional",
          "Personal trainer or coach",
          "Physical therapist or chiropractor",
          "None — this is my only current support",
        ],
        required: false,
      },
    ],
  },
  {
    sectionKey: "mindset_accountability",
    title: "Mindset & Accountability",
    questions: [
      {
        questionKey: "change_belief",
        label: "Which statement best describes how you think about your ability to change?",
        inputType: "single_select",
        options: [
          "I believe I can significantly change with the right effort and approach",
          "I believe change is possible but I have seen little evidence of it in myself",
          "I am not sure — part of me believes, part of me doubts",
          "I have struggled to believe I am capable of sustained change",
          "I believe this time can be different and I have a clear reason why",
        ],
        required: true,
      },
      {
        questionKey: "self_talk_after_setback",
        label: "When you miss a workout or have a bad nutrition day, what does your inner voice say?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "habit_pattern",
        label: "Which pattern most describes your relationship with goals and habits?",
        inputType: "single_select",
        options: [
          "All-or-nothing — I am either fully in or completely off the rails",
          "Strong starter — I begin motivated but fade after a few weeks",
          "Slow to start — but once I have momentum, I am hard to stop",
          "Fairly consistent — I show up even when I do not feel like it",
          "Perfectionist — I do not start unless conditions are exactly right",
        ],
        required: false,
      },
      {
        questionKey: "accountability_style",
        label: "What actually helps you follow through?",
        inputType: "multi_select",
        options: [
          "External check-ins — knowing someone will ask how I did",
          "Tracking and logging — seeing the data in front of me",
          "Paying for something — financial investment increases follow-through",
          "Social accountability — doing it with or around other people",
          "Internal drive — once I decide, I do not need external pressure",
          "Identity framing — behaving in a way that matches who I want to be",
          "Reminders and notifications — I genuinely need prompts",
        ],
        required: false,
      },
      {
        questionKey: "environmental_barriers",
        label: "Which of these makes healthy habits hardest for you?",
        inputType: "multi_select",
        options: [
          "My work schedule or hours are unpredictable",
          "My family or household routines make consistency difficult",
          "Travel disrupts my routines",
          "I start the day with good intentions but the day gets away from me",
          "I struggle most in the evenings",
          "I struggle most on weekends",
          "My environment makes discipline difficult",
          "None of these are major barriers",
        ],
        required: false,
      },
      {
        questionKey: "coach_support_when_struggling",
        label: "When you are struggling but not completely off track, what do you most need from your coach?",
        inputType: "single_select",
        options: [
          "Honesty — tell me what the data shows and do not soften it",
          "Encouragement — remind me of what I have done well",
          "Questions — ask me what is happening rather than telling me",
          "A reduced version — give me the minimum viable action",
          "Space — I am aware, I just need to work through it",
        ],
        required: false,
      },
      {
        questionKey: "previous_coaching_shame",
        label: "Have you ever felt that a previous coach, trainer, or program made you feel judged, shamed, or inadequate?",
        inputType: "single_select",
        options: ["Yes", "No"],
        required: false,
      },
      {
        questionKey: "previous_coaching_shame_details",
        label: "If yes, what happened and what do you not want repeated?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "setback_response",
        label: "How do you usually handle setbacks when life gets hard and the plan falls apart?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "failure_story",
        label: "What is the story you tell yourself about why you have not been able to maintain healthy habits long-term?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "five_year_vision",
        label: "What would it mean for your life if you were consistently healthy and fit for the next five years?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "something_to_prove",
        label: "Is there something about yourself you have always wanted to prove — to yourself, not to anyone else?",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "science_preference",
        label: "How important is it to you to understand why you are doing something?",
        inputType: "single_select",
        options: [
          "Very important — I want to understand the reasons behind recommendations",
          "Somewhat important — a brief explanation helps me commit",
          "Not very important — just tell me what to do",
          "It depends on the topic",
        ],
        required: false,
      },
      {
        questionKey: "ninety_day_identity",
        label: "Complete this sentence: In 90 days, I will be someone who...",
        inputType: "textarea",
        required: false,
      },
      {
        questionKey: "ai_coach_openness",
        label: "How do you feel about talking to an AI coach versus a human coach?",
        inputType: "single_select",
        options: [
          "Excited — I like that it is available any time and feels less judgmental",
          "Neutral — I am open to it and curious",
          "Somewhat skeptical — I will try it but I am not fully convinced yet",
          "I would prefer a human and see this as a supplement",
        ],
        required: false,
      },
    ],
  },
  { sectionKey: "spirit_new_beginnings",     title: "Spirit & New Beginnings",   questions: [] },
];

/** Look up a section config by its key */
export function getSectionConfig(sectionKey: string): SectionConfig | undefined {
  return SECTION_CONFIGS.find((s) => s.sectionKey === sectionKey);
}

/** Look up a section config by its display title */
export function getSectionByTitle(title: string): SectionConfig | undefined {
  return SECTION_CONFIGS.find((s) => s.title === title);
}
